title: Geonung Choi
url: "https://ddugel3.github.io"
baseurl: ""
description: Software researcher interested in embodied AI, robot locomotion, and efficient machine learning.
theme_skin: blue
chrome_mobile_color: "#2d7788"

sass:
  sass_dir: _sass
  style: compressed

compress-site: true
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development
